### ISSUE TITLE
Symlink File Mounting Issue

### ISSUE THREAD

**Issue by calebfavor** [ApsOps/filebeat-kubernetes#4]
My filebeat DaemonSet was not able to read any container log files using the provided yaml. I kept getting error: **stat (*logfile-path.log*) no such file or directory.**

To fix the issue I had to also mount the /var/log/pods directory into the container. 

I wasn't able to track down the exact change log, but I believe this is due to changes with how the log files are mounted in kubernetes 1.6.

My working daemonset:

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat
  labels:
    app: filebeat
spec:
  template:
    metadata:
      labels:
        app: filebeat
      name: filebeat
    spec:
      containers:
      - name: filebeat
        image: apsops/filebeat-kubernetes:v0.3
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
        env:
          - name: LOGSTASH_HOSTS
            value: my-host:my-port
          - name: LOG_LEVEL
            value: debug
        volumeMounts:
        - name: varlog
          mountPath: /var/log/containers
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlogpods
          mountPath: /var/log/pods
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/containers
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlogpods
        hostPath:
          path: /var/log/pods
```

PS. Thanks for putthing this project together, it saved my quite a bit of time.
